### ISSUE TITLE
Full Screen is klunky

### ISSUE THREAD

**Issue by robacarp** [vv-vim/vv#133]
Thanks for your work on vv here. 

<details><summary>The landscape of neovim frontends which work on MacOS isn't great. </summary>
I looked at <a href="https://github.com/qvacua/vimr">vimr</a> but they have a bunch of baked features for swift development I don't want. Of course <a href="https://github.com/rogual/neovim-dot-app">Neovim.app</a>, but it hasn't been updated in years. <a href="https://github.com/neovide/neovide">Neovide</a> claims to be a no-nonsense client but even after starting from scratch installing Rust and compiling it, it was clumsy. <a href="http://dinvim.com/">DinVim</a> looks promising, but it seems like they're going for a premium model of some sort. I'm not opposed to that, but I don't know if it's refined enough for that just yet.</details>

In the latest tagged release, the full screen mode of vv doesn't quite work right. The app does go full screen, but it doesn't get placed on it's own "desktop" and other app windows will float on top of it as if it was just a regular window. 

Thanks again.

vv Version 2.4.9 (2.4.9)
MacOS 12.0.1

**Comment by igorgladkoborodov** [comment]
Hi @robacarp, sorry for the late answer. VV has two fullscreen modes: the native fullscreen and the simple fullscreen. The default is simple fullscreen because it is faster, less animation when you switch apps. But you can switch to the original native fullscreen adding `VVset nosimplefullscreen` in your config. I recommend wrapping it with the `if exists('g:vv')` condition like this: https://github.com/vv-vim/vv/blob/main/README.md?plain=1#L92-L99

**Comment by robacarp** [comment]
@igorgladkoborodov thanks for the suggestion. That does correct the UI glitches I was seeing.

I think the problem I was seeing may be that the hotkey and menu item for full screen at `View -> Toggle Full Screen` puts the full screen behavior when it's configured as "simple" into a weird state. Sometimes the menu bar covers up line 1, for example. Perhaps there's a bug with that menu action?
