### ISSUE TITLE
Can I use <A-*> / <M-*> mappings?

### ISSUE THREAD

**Issue by delphinus** [vv-vim/vv#69]
I'm using many mappings using Option (⌥）key by `<A-` / `<M-`. I found these mappings cannot work on vv.

OS: macOS Catalina 10.15.7
Neovim: NVIM v0.5.0-6af64d384 (HEAD)
VV: v2.3.0

**Comment by igorgladkoborodov** [comment]
Hi @delphinus. Alt+key produces special symbols like ∆˚¬… etc. So currently you can make it work by mapping it with that special symbols. So instead of `<A-j>` you can map it as `<A-∆>`.

I will spend some time next week to make it work with Latin symbols as expected.

**Comment by delphinus** [comment]
Thx! I found it works, but some mappings still does not -- such as `<A-n>`. I input `Option+N` once, my Mac outputs no chars. And `Option+N` again, it outputs `˜`.

Anyway, I'm waiting for fixing until I can use latin symbols with `<A-`.

**Comment by igorgladkoborodov** [comment]
hey @delphinus, sorry for delay. Did not have a chance to work on this.

After a brief research I found that there are no consistent way to send Option + key combinations. It depends on terminal settings, UI client, keyboard layout etc. Ideally all mappings should work the same as mappings in terminal version of nvim, but again, it might be different depending on terminal emulator and it's settings.

I've made a draft of fix. It will send existing working mappings as before (for example `<A-∆>`) to make it backwards compatible. But it will send latin variant for those Option keyboard combination that expect additional symbol (for example `Option+i` will send `<A-i>`).

Also I've found that in insert mode Option combinations did not work correctly. It was impossible to type symbols like ∆˚¬ in insert mode. Fixed that too.

You can check how exactly it works in tests https://github.com/vv-vim/vv/pull/74/files#diff-a0d5dfbc278d4648bb22c745ea791937f2349f1dc39b998428c8a8ea3fcec7d6R126-R178

This is still WIP, I will wrap it up shortly. After this fix I want to make an additional optional setting to switch to "always-latin" Option-key combinations to make it send `<A-j>` for `Option+J` instead of `<A-∆>`.

**Comment by igorgladkoborodov** [comment]
hey @delphinus
The fix with option key is on the most recent version now: https://github.com/vv-vim/vv/releases/tag/v2.4.0
You can check #74 for detailed explanation how it work.

**Comment by delphinus** [comment]
Sorry for late. I found `<A-*>` mappings worked validly I expected. Thx for working!
